# Generated by Django 3.2 on 2020-06-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendido',
            fields=[
                ('cod_atendido', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_atendido', models.CharField(max_length=50)),
                ('ra_atendido', models.CharField(max_length=20)),
                ('nis_atendido', models.CharField(max_length=11)),
                ('nascimento_atendido', models.DateField()),
                ('rua_atendido', models.CharField(max_length=50)),
                ('numero_atendido', models.CharField(max_length=5)),
                ('bairro_atendido', models.CharField(max_length=30)),
                ('cidade_atendido', models.CharField(max_length=30)),
                ('telefone_atendido', models.CharField(max_length=11)),
                ('email_atendido', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'atendido',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('cod_atividade', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('cod_espaco', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_espaco', models.CharField(max_length=20)),
                ('lugares_espaco', models.IntegerField()),
            ],
            options={
                'db_table': 'espaco',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('cod_instrutor', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_instrutor', models.CharField(max_length=50)),
                ('especialidade_instrutor', models.CharField(max_length=9)),
                ('rg_instrutor', models.CharField(max_length=9)),
                ('cpf_instrutor', models.CharField(max_length=11)),
                ('nascimento_instrutor', models.DateField()),
                ('rua_instrutor', models.CharField(max_length=50)),
                ('numero_instrutor', models.CharField(max_length=5)),
                ('bairro_instrutor', models.CharField(max_length=30)),
                ('cidade_instrutor', models.CharField(max_length=30)),
                ('telefone_instrutor', models.CharField(max_length=11)),
                ('email_instrutor', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'instrutor',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('cod_oficina', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_oficina', models.CharField(max_length=50)),
                ('descricao_oficina', models.CharField(max_length=500)),
                ('objetivo_oficina', models.CharField(max_length=100)),
                ('publico_oficina', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'oficina',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('cod_periodo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('dia_periodo', models.CharField(max_length=13)),
                ('periodo_periodo', models.CharField(max_length=5)),
                ('horario_periodo', models.TimeField()),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('cod_responsavel', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_responsavel', models.CharField(max_length=50)),
                ('rg_responsavel', models.CharField(max_length=9)),
                ('nis_responsavel', models.CharField(max_length=11)),
                ('cpf_responsavel', models.CharField(max_length=11)),
                ('nascimento_responsavel', models.DateField()),
                ('rua_responsavel', models.CharField(max_length=50)),
                ('numero_responsavel', models.CharField(max_length=5)),
                ('bairro_responsavel', models.CharField(max_length=30)),
                ('telefone_responsavel', models.CharField(max_length=11)),
                ('email_responsavel', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'responsavel',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('cod_turma', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=15)),
                ('cod_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.atividade')),
            ],
            options={
                'db_table': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Turma_Atendido',
            fields=[
                ('cod_turma_atendido', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cod_atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.atendido')),
                ('cod_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.turma')),
            ],
            options={
                'db_table': 'turma_atendido',
                'unique_together': {('cod_atendido', 'cod_turma')},
            },
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('cod_chamada', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data_chamada', models.DateField()),
                ('atendidos_presentes', models.ManyToManyField(to='caritas_app.Atendido')),
                ('cod_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.turma')),
            ],
            options={
                'db_table': 'chamada',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='cod_instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.instrutor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='cod_oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.oficina'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='cod_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.responsavel'),
        ),
        migrations.CreateModel(
            name='Turma_Atendido_Chamada',
            fields=[
                ('cod_turma_atendido_chamada', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('presente_turma_atendido_chamada', models.BooleanField()),
                ('cod_chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.chamada')),
                ('cod_turma_atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.turma_atendido')),
            ],
            options={
                'db_table': 'turma_atendido_chamada',
                'unique_together': {('cod_turma_atendido', 'cod_chamada')},
            },
        ),
        migrations.CreateModel(
            name='Responsavel_Atividade',
            fields=[
                ('cod_responsavel_atividade', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cod_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.atividade')),
                ('cod_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.responsavel')),
            ],
            options={
                'db_table': 'reponsavel_atividade',
                'unique_together': {('cod_atividade', 'cod_responsavel')},
            },
        ),
        migrations.CreateModel(
            name='Periodo_Atividade',
            fields=[
                ('cod_periodo_atividade', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cod_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.atividade')),
                ('cod_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.periodo')),
            ],
            options={
                'db_table': 'periodo_atividade',
                'unique_together': {('cod_periodo', 'cod_atividade')},
            },
        ),
        migrations.CreateModel(
            name='Espaco_Atividade',
            fields=[
                ('cod_espaco_atividade', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cod_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.atividade')),
                ('cod_espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caritas_app.espaco')),
            ],
            options={
                'db_table': 'espaco_atividade',
                'unique_together': {('cod_espaco', 'cod_atividade')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='atividade',
            unique_together={('cod_instrutor', 'cod_oficina')},
        ),
    ]
