# Generated by Django 3.2 on 2020-06-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caritas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('cod_atividade', 'nome_turma')},
        ),
    ]
